# coding: utf-8

"""
    Organization structure API

    Welcome on the documentation for the Organization Structure API 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: www.lucca.fr
"""

from lucca_organization_python_sdk.paths.api_v3_axis_sections.post import CreateNewAxisSectionRaw
from lucca_organization_python_sdk.paths.api_v3_axis_sections_axis_section_id.delete import DeleteByIdRaw
from lucca_organization_python_sdk.paths.api_v3_axis_sections_axis_section_id.get import GetByIdRaw
from lucca_organization_python_sdk.paths.api_v3_axes.get import ListRaw
from lucca_organization_python_sdk.paths.api_v3_axis_sections.get import List0Raw
from lucca_organization_python_sdk.paths.api_v3_axis_sections_axis_section_id.put import UpdateByIdRaw


class AxisSectionsApiRaw(
    CreateNewAxisSectionRaw,
    DeleteByIdRaw,
    GetByIdRaw,
    ListRaw,
    List0Raw,
    UpdateByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
