# coding: utf-8

"""
    Organization structure API

    Welcome on the documentation for the Organization Structure API 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: www.lucca.fr
"""

from lucca_organization_python_sdk.paths.api_v3_axis_sections.post import CreateNewAxisSection
from lucca_organization_python_sdk.paths.api_v3_axis_sections_axis_section_id.delete import DeleteById
from lucca_organization_python_sdk.paths.api_v3_axis_sections_axis_section_id.get import GetById
from lucca_organization_python_sdk.paths.api_v3_axes.get import List
from lucca_organization_python_sdk.paths.api_v3_axis_sections.get import List0
from lucca_organization_python_sdk.paths.api_v3_axis_sections_axis_section_id.put import UpdateById
from lucca_organization_python_sdk.apis.tags.axis_sections_api_raw import AxisSectionsApiRaw


class AxisSectionsApi(
    CreateNewAxisSection,
    DeleteById,
    GetById,
    List,
    List0,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AxisSectionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AxisSectionsApiRaw(api_client)
