# coding: utf-8

"""
    Organization structure API

    Welcome on the documentation for the Organization Structure API 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: www.lucca.fr
"""

from lucca_organization_python_sdk.paths.api_v3_departments.get import GetAll
from lucca_organization_python_sdk.paths.api_v3_departments_department_id.get import GetById
from lucca_organization_python_sdk.paths.api_v3_departments_tree.get import ListTree
from lucca_organization_python_sdk.apis.tags.departments_api_raw import DepartmentsApiRaw


class DepartmentsApi(
    GetAll,
    GetById,
    ListTree,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DepartmentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DepartmentsApiRaw(api_client)
