# coding: utf-8

"""
    Organization structure API

    Welcome on the documentation for the Organization Structure API 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: www.lucca.fr
"""

from lucca_organization_python_sdk.paths.api_v3_departments.get import GetAllRaw
from lucca_organization_python_sdk.paths.api_v3_departments_department_id.get import GetByIdRaw
from lucca_organization_python_sdk.paths.api_v3_departments_tree.get import ListTreeRaw


class DepartmentsApiRaw(
    GetAllRaw,
    GetByIdRaw,
    ListTreeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
